config/routes.rb
SampleApp::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :projects
  
  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :title, :description, :location, :start, :end, :goal, :pledged, :backers, :user_id
  validates :user_id, presence: true
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :title, :description, :location, :start, :end, :goal, :pledged, :backers
  belongs_to :user

  validates :title, presence: true, length: { maximum: 140 }
  validates :user_id, presence: true
  default_scope order: 'projects.created_at DESC'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password
  has_many :projects, dependent: :destroy

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :signed_in_user, only: [:create, :destroy]

  def index
    @projects = Project.paginate(page: params[:page])
  end

  def show
    @project = Project.find(params[:id])
  end

  def create
    @project = current_user.projects.build(params[:project])
    if @project.save
      flash[:success] = "Project created!"
      redirect_to root_url
    else
      render 'static_pages/home'
    end
  end

  def new
    @project = Project.new
  end

  def destroy
    Project.find(params[:id]).destroy
    flash[:success] = "Project destroyed."
    redirect_to users_url
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@project = current_user.projects.build if signed_in?
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_filter :correct_user,   only: [:edit, :update]
  before_filter :admin_user,     only: :destroy

  def show
    @user = User.find(params[:id])
    @projects = @user.projects.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end


    private


    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Barracudaz"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def current_user?(user)
    user == current_user
  end


  def signed_in_user
    unless signed_in?
      store_location
    #  redirect_to signin_url, notice: "Please sign in."
    end
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	# Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to "BARRACUDAZ",   root_path %>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="#">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "barracudaz", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <!--<li><%= link_to "Help", help_path %></li>-->
          
            <li><%= link_to "Projects", projects_path %></li>
            <li><%= link_to "Designers", users_path %></li>
            <% if signed_in? %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li><%= link_to "Post Project", new_project_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
   <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/projects/_project.html.erb
<li class="project span3">
  <article class="thumbnail">
                <!--<%= gravatar_for project.user, size: 200 %> -->
                <img class="gravatar" src="http://jazcollection.com/images/demo/x403.116.jpg">
                
                 <div class="clear" />
                <h4><%= link_to project.title, project %> <% if !current_user.nil? && current_user.admin? %>
    |  <%= link_to "delete", project, method: :delete, data: { confirm: "You sure?" } %>
    <% end %> </h4>
                <h5><%= project.description %></h5>
                <h6><i class="icon-globe"></i><%= project.location %></h6>
                <ul>
                  <h6>Start: <%= project.start %> </h6>
                  <h6>End: <%= project.end %> </h6>
                  <h6>Goal: <%= project.goal %> </h6>
                  <h6>Pledged: <%= project.pledged %></h6>
                  <h6>Backers: <%= project.backers %></h6>
                </ul>
              </article>
</li>

app/views/projects/index.html.erb
<% provide(:title, 'All Projects') %>
<h1>All Projects</h1>
<% @projects = Project.paginate(:page => params[:page], :per_page => 12)%>
<%= will_paginate %>
<div class="clear"></div>
<div class="row-fluid">
<ul class="thumbnails">
  <%= render @projects %>
</ul>
</div>

<%= will_paginate %>
<div class="clear"></div>

app/views/projects/new.html.erb
<h1> Add a new project </h1>

<%= form_for @project do |form| %>
	<% if @project.errors.any? %>
		<h2>Errors:</h2>
		<ul>
			<% @project.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	<% end %>
	<p>
		<%= form.label :title %> <br/>
		<%= form.text_field :title %>
	</p>
	<p>
		<%= form.label :description %> <br/>
		<%= form.text_area :description %>
	</p>
	<p>
		<%= form.label :location %> <br/>
		<%= form.text_field :location %>
	</p>
	<p>
		<%= form.label :pledged %> <br/>
		<%= form.text_field :pledged %>
	</p>
	<p>
		<%= form.label :goal %> <br/>
		<%= form.text_field :goal %>
	</p>
	<p>
		<%= form.label :start %> <br/>
		<%= select_date Date.today, :prefix => :start %>
	</p>
	<p>
		<%= form.label :end %> <br/>
		<%= select_date Date.today, :prefix => :end %>
	</p>
	<p>
		<%= form.label :backers %> <br/>
		<%= form.text_field :backers %>
	</p>
	<p>
		<%= form.submit "Add a New Project" %> 
	</p>

<% end %>

app/views/projects/show.html.erb
<% provide(:title, @project.title) %>

    	<img class="gravatar" src="http://jazcollection.com/images/demo/x403.116.jpg">

      <h1>
        <%= @project.title %>
      </h1>
      <h2>
        <%= @project.description %>
      </h2>
      <h6><i class="icon-globe"></i><%= @project.location %></h6>
                <ul>
                  <h6>Start: <%= @project.start %> </h6>
                  <h6>End: <%= @project.end %> </h6>
                  <h6>Goal: <%= @project.goal %> </h6>
                  <h6>Pledged: <%= @project.pledged %></h6>
                  <h6>Backers: <%= @project.backers %></h6>
                </ul>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_project_form.html.erb
<%= form_for(@project) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :title, placeholder: "Compose new title..." %>
  </div>
  <div class="field">
    <%= f.text_area :description, placeholder: "Description" %>
  </div>
  <div class="field">
    <%= f.text_area :location, placeholder: "Location" %>
  </div>
  <div class="field">
    <%= f.text_area :start, placeholder: "Start Date" %>
  </div>
    <div class="field">
    <%= f.text_area :end, placeholder: "End Date" %>
  </div>
  <div class="field">
    <%= f.text_area :goal, placeholder: "Goal" %>
  </div>
  <div class="field">
    <%= f.text_area :pledged, placeholder: "Pledged" %>
  </div>
    <div class="field">
    <%= f.text_area :backers, placeholder: "Backers" %>
  </div>

  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user, size: 52 %>
</a>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.projects.count, "project") %>
</span>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
 Barracudaz provides crowd funding and manufacturing for designers
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Barracudaz at ....
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Please contact us with questions. 
</p>

app/views/static_pages/home.html.erb
  <div class="center hero-unit">
  <h1>Discover & Fund Fashion</h1>

  <h2>
    Barracudaz provides crowd funding and manufacturing for designers
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
  </div>
  <div class="row-fluid">
            <li class="span4">
              <div class="center" style="width:150px; margin:0px auto;padding: 10px 0;
    display: block;">
                <img src="http://www.smsdiesel.com.au/images/logo's_icons/Globe-Icon.jpg" style="width:100%"/>
              </div>
              <h2><%= link_to "Find Fashion", projects_path %></h2>
            </li>
            <ul class="thumbnails">
            <li class="span4">
              <div class="center" style="width:150px; margin:0px auto;padding: 10px 0;
    display: block;">
                <img src="http://www.smsdiesel.com.au/images/logo's_icons/Globe-Icon.jpg" style="width:100%"/>
              </div>
              <h2> <%= link_to "Discover Designers", users_path %></h2>
            </li>
            <li class="span4">
              <div class="center" style="width:150px; margin:0px auto; padding: 10px 0;
    display: block;">
                <img src="http://www.smsdiesel.com.au/images/logo's_icons/Globe-Icon.jpg" style="width:100%"/>
              </div>
              <h2><%= link_to "Post a Project", signup_path %></h2>

            </li>
          </ul>
        </div>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
    <% if !current_user.nil? && current_user.admin? %>
    |  <%= link_to "delete", user, method: :delete, data: { confirm: "You sure?" } %>
    <% end %>

</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %> 
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All Designers') %>
<h1>All Designers</h1>

<% @users = User.paginate(:page => params[:page], :per_page => 12)%>
<%= will_paginate %>
<div class="clear"></div>
<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>
<div class="clear"></div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="span8">
    <% if @user.projects.any? %>
      <h3>Projects (<%= @user.projects.count %>)</h3>
      <ol class="projects">
        <%= render @projects %>
      </ol>
      <%= will_paginate @projects %>
    <% end %>
  </div>
</div>